name: Build macOS GCC

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update packages
      run: |
        brew install coreutils
        brew install mpich

    - name: Build NCEPLIBS-external
      run: |
        export FC=mpif90
        export CC=mpicc
        export CXX=mpic++
        echo "FC = ${FC}"
        echo "CC = ${CC}"
        echo "CXX= ${CXX}"
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install .. 2>&1 | tee log.cmake
        make -j2 2>&1 | tee log.make
