name: Build macOS GCC

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update packages
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install coreutils mpich

    - name: Build NCEPLIBS-external
      run: |
        export CC=mpicc
        export FC=mpif90gfortran-9
        export CXX=mpic++
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install .. 2>&1 | tee log.cmake
        make -j2 2>&1 | tee log.make
